abstract class TodoStatesClass {}
class TodoInitialState extends TodoStatesClass{}
class TodoChangeBottomNavBarState extends TodoStatesClass{}
class TodoCreateDataBaseState extends TodoStatesClass{}
class TodoUpdateDataBaseState extends TodoStatesClass{}
class TodoDeleteDataBaseState extends TodoStatesClass{}
class TodoGetDataBaseState extends TodoStatesClass{}
class TodoInsertDataBaseState extends TodoStatesClass{}
class TodoChangeBottomSheetState extends TodoStatesClass{}
class ChangeAppMode extends TodoStatesClass{}